version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: 6-plus
    environment:
      MYSQL_ROOT_PASSWORD: team6
      MYSQL_DATABASE: plus
      MYSQL_USER: team6
      MYSQL_PASSWORD: team6
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: